# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DukeHealthiOSSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DukeHealthiOSSDK

	pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'UICKeyChainStore'
    pod 'ZAlertView'
    pod 'base64url', '~> 1.0'
    pod 'Toast-Swift', '~> 4.0.0'
  target 'DukeHealthiOSSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DukeHealthiOSSDKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
